"""
Telegram Bot — Polling Mode (for local testing)
================================================
Run this to test the Telegram bot locally.
No public URL or deployment needed!

Usage:
    source venv/bin/activate
    python scripts/run_telegram_polling.py
"""

import sys
import asyncio
import logging
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from dotenv import load_dotenv
load_dotenv()

import os
from telegram import Update
from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes

logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO
)
logger = logging.getLogger(__name__)


# ── Handlers ──────────────────────────────────────────────────────────────────

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle /start command."""
    await update.message.reply_text(
        "👋 *Welcome to Fair Districts GA AI!*\n\n"
        "Ask me anything about Georgia redistricting:\n\n"
        "📊 _'Which districts have over 50% Black VAP?'_\n"
        "🗺 _'Compare the 2021 and 2024 Senate maps'_\n"
        "📈 _'Show me the most Democratic House districts'_\n\n"
        "I'll answer with data and charts! This may take 20-30 seconds. ☕",
        parse_mode="Markdown"
    )


async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle /help command."""
    await update.message.reply_text(
        "*Example questions you can ask:*\n\n"
        "• Which Senate districts have >50% BVAP in the 2024 map?\n"
        "• How many majority-minority districts are in the House?\n"
        "• Compare the 2021 and 2024 Senate maps for minority representation\n"
        "• What is the partisan lean of Congressional district 5?\n"
        "• Which districts saw the biggest change in BVAP between 2021 and 2024?\n"
        "• Show me the demographic breakdown of Senate remedy maps\n\n"
        "_Responses include a chart when helpful!_",
        parse_mode="Markdown"
    )


async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle any text message — run it through the AI crew."""
    question = update.message.text.strip()
    chat_id = update.effective_chat.id

    logger.info(f"Question from {chat_id}: {question}")

    # Let user know we're working (important for 20-30s wait)
    await context.bot.send_chat_action(chat_id=chat_id, action="typing")
    thinking_msg = await update.message.reply_text(
        "🤔 Analyzing redistricting data... (this takes ~20 seconds)"
    )

    try:
        from backend.crews.analysis_crew import FairDistrictsGACrew, is_complex_question

        crew = FairDistrictsGACrew()

        if is_complex_question(question):
            result = crew.full_analysis(question)
        else:
            result = crew.quick_answer(question)

        # Delete the "thinking" message
        await thinking_msg.delete()

        # Send the answer
        answer = result.answer
        # Telegram has 4096 char limit per message
        if len(answer) > 4000:
            answer = answer[:3997] + "..."

        await update.message.reply_text(answer, parse_mode="Markdown")

        # Send chart if generated
        if result.has_chart:
            await context.bot.send_chat_action(chat_id=chat_id, action="upload_photo")
            with open(result.chart_path, "rb") as photo:
                await update.message.reply_photo(
                    photo=photo,
                    caption="📊 Chart generated by Fair Districts GA AI | fairdistrictsga.org"
                )

    except Exception as e:
        logger.error(f"Error handling message: {e}", exc_info=True)
        await thinking_msg.edit_text(
            f"❌ Sorry, I had trouble analyzing that. Please try again.\n\n"
            f"_Error: {str(e)[:100]}_",
            parse_mode="Markdown"
        )


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    token = os.getenv("TELEGRAM_BOT_TOKEN")
    if not token:
        print("❌ TELEGRAM_BOT_TOKEN not found in .env")
        print("   See docs/telegram_setup.md for instructions")
        sys.exit(1)

    print(f"🤖 Starting Telegram bot (polling mode)...")
    print(f"   LLM Provider: {os.getenv('LLM_PROVIDER', 'ollama')}")
    print(f"   Find your bot on Telegram and send a message!")
    print(f"   Press Ctrl+C to stop\n")

    app = Application.builder().token(token).build()

    app.add_handler(CommandHandler("start", start))
    app.add_handler(CommandHandler("help", help_command))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))

    app.run_polling(allowed_updates=Update.ALL_TYPES)


if __name__ == "__main__":
    main()
